---
title: "Data_Science_Final"
author: "Candace Haghighi"
date: "11/22/2017"
output: 
runtime: shiny
---
>Quick Intro... Please make sure that when you type in your section that the code chunk does not push too far down! This will 'bleed' into the next person's section and may cause issues when merging - thank you!!


```{r, Claire section (line 10-110; used for bringing in, cleaning, merging, etc. data)}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(ggridges)
library(ggthemes)
library(forcats)
library(viridis)
library(plotly)
library(knitr)
library(kableExtra)
library(shiny)
library(rvest)
library(httr)
```

```{r}
# cleaning the data
hospital_data = read_csv(file = "./data/Hospital_General_Information.csv", col_names = TRUE) %>% 
  clean_names() %>%
  select(provider_id, hospital_name, city, state, zip_code, hospital_type, hospital_ownership, hospital_overall_rating, patient_experience_national_comparison, location) %>% 
  mutate(hospital_overall_rating = as.numeric(hospital_overall_rating)) %>%
  filter(!is.na(hospital_overall_rating)) %>%
  separate(location, into = c("address", "coordinates"), sep = "\\(") %>% 
  mutate(coordinates = str_sub(coordinates, 1, -2)) %>% 
  separate(coordinates, into = c("Latitudes", "Longitudes"), sep = ",")
```

```{r, eval = FALSE}
# Do not run code between this and the next comment - the `geocode` function takes a long time
hospital_data_missing = read_csv(file = "./data/Hospital_General_Information.csv", col_names = TRUE) %>% 
  clean_names() %>%
  select(provider_id, hospital_name, city, state, zip_code, hospital_type, hospital_ownership, hospital_overall_rating, patient_experience_national_comparison, location) %>% 
  mutate(hospital_overall_rating = as.numeric(hospital_overall_rating)) %>%
  filter(!is.na(hospital_overall_rating)) %>%
  separate(location, into = c("address", "coordinates"), sep = "\\(") %>% 
  mutate(coordinates = str_sub(coordinates, 1, -2)) %>% 
  filter(is.na(coordinates)) %>%
  mutate(coordinates = map(address, ggmap::geocode))

hospital_data_missing_clean <- hospital_data_missing %>% 
  unnest() %>%
  rename(Longitudes = lon, Latitudes = lat)
  
hospital_data_missing_2 <- hospital_data_missing_clean %>% 
  filter(is.na(Longitudes)) %>%
  mutate(coordinates_2 = map(hospital_name, ggmap::geocode))

hospital_data_missing_2_clean <- hospital_data_missing_2 %>% 
  select(everything(), -Longitudes, -Latitudes) %>% 
  unnest() %>%
  rename(Longitudes = lon, Latitudes = lat)

hospital_data_2 <- 
  bind_rows(hospital_data_missing_clean, hospital_data_missing_2_clean) %>%
  drop_na() %>%
  select(c(provider_id:address), Latitudes, Longitudes) %>%
  mutate(Latitudes = as.character(Latitudes),
         Longitudes = as.character(Longitudes)) %>% 
  bind_rows(hospital_data) %>%
  drop_na()

write_csv(hospital_data_2, "./data/hospital_data_2.csv")
```

```{r}
# Load hospital_data_2.csv below for results of above code chunk
hospital_data_2 <- read_csv("./data/hospital_data_2.csv")
```

```{r}
# hospital rating based on hospital type (boxplot)
box_ggplot_type =
hospital_data_2 %>% 
   mutate(hospital_type = fct_reorder(hospital_type, hospital_overall_rating)) %>%
ggplot(aes(x = hospital_type, y = hospital_overall_rating, group = hospital_type)) + geom_boxplot(aes(color = hospital_type)) + labs(title = "Distribution of Hospital Rating Based on Hospital Type", x = "Hospital Type", y = "Hospital Rating") + theme_classic() + theme(axis.text.x = element_text(hjust = 1), plot.title = element_text(hjust = 0.5))
box_ggplot_type

# hospital rating based on ownership (boxplot)
box_ggplot_owner =
hospital_data_2 %>% 
   mutate(hospital_ownership = fct_reorder(hospital_ownership, hospital_overall_rating)) %>%
ggplot(aes(x = hospital_ownership, y = hospital_overall_rating, group = hospital_ownership)) + geom_boxplot(aes(color = hospital_ownership)) + labs(title = "Distribution of Hospital Rating Based on Hospital Ownership", x = "Hospital Ownership", y = "Hospital Rating") + theme_classic() + theme(axis.text.x = element_text(angle = 120, hjust = 1)) + theme(axis.text.x = element_text(hjust = 1), plot.title = element_text(hjust = 0.5))
ggplotly(box_ggplot_owner)

# hospital rating distribution (barplot)
hospital_data_2 %>% 
  mutate(hospital_overall_rating = as.character(hospital_overall_rating)) %>%
  count(hospital_overall_rating) %>% 
  mutate(hospital_overall_rating = fct_reorder(hospital_overall_rating, n)) %>% 
  plot_ly(x = ~hospital_overall_rating, y = ~n, color = ~hospital_overall_rating, type = "bar", colors = "Set2") %>%
   layout(legend = list(x = 100, y = 0.5)) %>%
    layout(
    title = "Distribution of Hospital Rating") %>%
    layout(yaxis = list(title = 'Total number of Hospitals')) %>%
    layout(xaxis = list(title = 'Hospital Rating'))

# hospital rating and Patient Experience Level (Scatter plot)
scatter_patient = hospital_data_2 %>%
  filter(!(patient_experience_national_comparison == "Not Available")) %>%
  ggplot(aes(x = patient_experience_national_comparison, y = hospital_overall_rating, color = hospital_overall_rating)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() + labs(title = "Hospital Rating and Patient Experience level", x = "Patient Experience Level", y = "Hospital Rating") +
  theme_classic()
ggplotly(scatter_patient)
```

##Any additional plots and changes 

```{r, Carolina section 230 - 330 }

library(rvest)
library(httr)


hospitalranks_html <- read_html("https://www.usnews.com/info/blogs/press-room/articles/2016-08-02/us-news-announces-the-201617-best-hospitals")

hospitals <- hospitalranks_html %>% html_nodes(".ad-in-text-target+ .ad-in-text-target h2 , .ad-in-text-target:nth-child(5) li") %>% html_text() %>% data.frame() %>% rename(hospitals = ".") %>% filter(hospitals != "2016–17 Best Hospitals Honor Roll")

```

```{r function for scraping hospital rankings from Honor Roll list (can select for different years) when it is arranged in a table with rank, hospital name, and number of points}

honor_roll_scrape <- function(url) {

honor_roll_html <- read_html(url)

rank <- honor_roll_html %>% html_nodes("td:nth-child(1)") %>% html_text() %>% data.frame() %>% rename(rank = ".")

hospital_name <- honor_roll_html %>% html_nodes("td:nth-child(2)") %>% html_text() %>% data.frame() %>% rename(hospital = ".")

points <- honor_roll_html %>% html_nodes("td:nth-child(3)") %>% html_text() %>% data.frame() %>% rename(points = ".") %>% mutate(points = as.numeric(as.character(points))) 

hospitals_honor_roll <- cbind(rank, hospital_name, points)

hospitals_honor_roll <- hospitals_honor_roll[2:21,]
}


```

```{r 2016-2017 Honor Roll hospitals with points}
hospital_honor_roll_2016 <- honor_roll_scrape("https://web.archive.org/web/20160816171510/http://health.usnews.com/health-care/best-hospitals/articles/best-hospitals-honor-roll-and-overview")

#web.archive.org August 16, 2016 
```


```{r}
#2017-2018 Honor Roll rankings, with points (maximum 480)

hospital_honor_roll_2017 <- honor_roll_scrape("https://health.usnews.com/health-care/best-hospitals/articles/best-hospitals-honor-roll-and-overview")

```

```{r}
#Hospital rankings by region--New York region. This first part works. 

ny_hospitalranks_html <- read_html("https://health.usnews.com/best-hospitals/area/new-york-ny")

ny_hospitals <- ny_hospitalranks_html %>% html_nodes(".search-result-link") %>% html_text() %>% data.frame() %>% rename(hospitals = ".") 
```


```{r, Candace section 340 - 440}
##Creating new data set w/ normalized column values for points
hospital_honor_roll_2016_newc = hospital_honor_roll_2016 %>%
##used normalized value (b-a)*(W-c)/(d+c)+a
mutate(new_score = (4 * points/448 + 1)) 

##Create vector
provider_id = c("240010", "360180", "220071", "210009", "050376", "330101", "050454", "140281", "390223", "330214", "260032", "390164", "220110", "050441", "330024", "340030", "050625", "230046", "450358", "060024")

##Add column to hospital_honor_roll_2016
hospital_honor_roll_2016_new <- cbind(hospital_honor_roll_2016_newc, provider_id)

##Merging w/ new column
Merged_dataset <- full_join(hospital_honor_roll_2016_new, hospital_data_2, by = "provider_id")

medicare_hospitals <- Merged_dataset %>% select(hospital, hospital_name, provider_id, hospital_overall_rating) %>% mutate(score = hospital_overall_rating, ranking_type = "medicare") %>% select(hospital, hospital_name, provider_id, score, ranking_type)

usnews_hospitals <- Merged_dataset %>% select(hospital,hospital_name, provider_id, new_score) %>% mutate(score = new_score, ranking_type = "usnews") %>% select(hospital, hospital_name, provider_id, score, ranking_type)

medicare_usnews <- rbind(medicare_hospitals, usnews_hospitals)

# Additional scatterplot - not used
medicare_usnews %>%
  ggplot(aes(x = hospital, y = score, col = ranking_type)) +
  geom_point() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

medicare_usnews %>%
  arrange(desc(score)) %>% 
  mutate(hospital = as.factor(hospital)) %>% 
  ggplot(aes(x = hospital, y = score, fill = ranking_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme(axis.text.x = element_text(angle = 70, hjust = 1))

# Creates a chart of the differences between the USNews and Medicare scores
medicare_usnews %>% 
  drop_na() %>% 
  spread(key = ranking_type, value = score) %>%
  mutate(score_diff = usnews - medicare) %>%
  mutate(pos_score_diff = ifelse(score_diff < 0, "Medicare > USNews", "USNews > Medicare")) %>% 
  mutate(hospital = fct_reorder(hospital, score_diff)) %>%
  ggplot(aes(hospital, score_diff, fill = pos_score_diff)) +
  geom_col() +
  coord_flip() +
  ylab("USNews score - Medicare score") +
  scale_fill_discrete(name = "")
```
```{r, logit}
##logistic modelling - binary outcome (patient experience - above and below national average)

##recode model 
hospital_data_logistic_regression =  hospital_data_2 %>%
filter(patient_experience_national_comparison != "Not Available") %>%
filter(patient_experience_national_comparison != "Same as the national average") %>%
mutate(patient_experience_national_comparison = recode(patient_experience_national_comparison, "Above the national average" = "1", "Below the national average" = "0"))

##making column 9 numeric with lapply
hospital_data_logistic_regression[,9] <- lapply(hospital_data_logistic_regression[,9], as.numeric)

##using glm with binomial distribution for model 
mylogit <- glm(patient_experience_national_comparison ~ hospital_ownership + hospital_overall_rating + hospital_type, data = hospital_data_logistic_regression, family = "binomial")



##revising data set to collapse government
hospital_data_logistic_regression_comp <- hospital_data_logistic_regression %>%
mutate(hospital_ownership = recode(hospital_ownership, "Government - Local" = "Government", "Government - State" = "Government", "Government - Hospital District or Authority" = "Government", "Government - Federal" = "Government")) 



##creating function to run regression model
hospitaldata_logm = function(df){
glm(patient_experience_national_comparison ~ hospital_ownership + hospital_overall_rating + hospital_type, data = hospital_data_logistic_regression_comp, family = "binomial")
}

hospital_data_lr_df = 
  hospital_data_logistic_regression_comp %>% 
  nest(provider_id:patient_experience_national_comparison) %>%
  mutate(models = map(data, hospitaldata_logm),
         results = map(models, broom::tidy)) %>%
  select(results) %>% 
  unnest() 

hospital_data_lr_df <- hospital_data_lr_df[c(1, 2, 3, 4, 5, 6, 7, 8),]   


kable(hospital_data_lr_df, caption = "Model Componnents of our patient experience model") %>%
kable_styling(bootstrap_options = c("striped", "hover"))

##May not be able to run with package kableExtra

#kable(hospital_data_lr_df, caption = "Model Componnents of our patient experience model") %>%
  #kable_styling("striped", full_width = F) %>%
  #column_spec(5, bold = T) %>%
  #row_spec(7:8, bold = T, color = "white", background = "#D7261E") %>%
  #row_spec(3, bold = T, color = "white", background = "#D7261E") 
```



```{r shiny code geographic distribution of star rankings}

hospital_data_2 <- read_csv("./data/hospital_data_2.csv")

hospital_data_regions <- hospital_data_2 %>%
  mutate(region = ifelse(grepl("ME|NH|VT|MA|RI|CT", state), "New England", ifelse(grepl("NY|PA|NJ", state), "Middle Atlantic", ifelse(grepl("WI|MI|IL|IN|OH", state), "East North Central", ifelse(grepl("ND|SD|NE|KS|MN|IA|MO", state), "West North Central", ifelse(grepl("DE|MD|DC|VA|WV|NC|SC|GA|FL", state), "South Atlantic", ifelse(grepl("KY|TN|MS|AL", state), "East South Central", ifelse(grepl("OK|TX|AR|LA", state), "West South Central", ifelse(grepl("ID|MT|WY|NV|UT|CO|AZ|NM", state), "Mountain", ifelse(grepl("AK|WA|OR|CA|HI", state), "Pacific", "U.S. Territories")))))))))) 


star_choice <- hospital_data_regions %>% 
  distinct(hospital_overall_rating) %>% arrange(desc(hospital_overall_rating))
# selectInput widget
shiny::selectInput("star_choice", label = h3("Select Star"),
            choices = star_choice, selected = "5")

regions <- hospital_data_regions %>% 
  distinct(region) %>% pull()
# selectInput widget
shiny::selectInput("region_choice", label = h3("Select Region"),
            choices = regions, selected = "New England")

#map plot
renderPlotly({ 
  
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showland = TRUE,
  landcolor = toRGB("gray95"),
  subunitcolor = toRGB("gray85"),
  countrycolor = toRGB("gray85"),
  countrywidth = 0.5,
  subunitwidth = 0.5
)

filter(hospital_data_regions, hospital_overall_rating == input$star_choice) %>%
  plot_geo(lat = ~Latitudes, lon = ~Longitudes, text = ~paste(hospital_name, city, state, sep = "<br />"), marker=list(color="blue" , size=5 , opacity=0.4)) %>%
  layout(title = 'Hospital Rankings (Hover for Hospital)', geo = g)
})



#bar plot by region

renderPlotly({ 
  hospital_data_regions %>%
  filter(hospital_overall_rating != "Not Available") %>%
  filter(region == input$region_choice) %>%
  mutate(hospital_overall_rating = as.numeric(hospital_overall_rating)) %>%
  group_by(region, state, hospital_overall_rating) %>%
  mutate(num_hospitals = n()) %>%
  plot_ly(x = ~hospital_overall_rating, y = ~num_hospitals,color = ~state, type = "bar") %>% 
  layout(title = "Number of hospitals per hospital rating, by state", margin = list(b = 75)) 
})

```


Other plotly code:

```{r}
box_ggplot_owner =
hospital_data_2 %>% 
  filter(hospital_ownership != "Tribal") %>%
  mutate(hospital_ownership = as.factor(hospital_ownership)) %>%
  mutate(hospital_overall_rating =  as.character(hospital_overall_rating)) %>%
  group_by(hospital_ownership) %>%
  count(hospital_overall_rating) %>%
  spread(key=hospital_overall_rating, value=n) 

box_ggplot_owner[is.na(box_ggplot_owner)] <- 0

box_ggplot_owner %>%
  plot_ly(x = ~hospital_ownership, y = ~ `1`, type = 'bar', name = 'Rating 1') %>%
  add_trace(y = ~ `2`, name = 'Rating 2') %>%
  add_trace(y = ~ `3`, name = 'Rating 3') %>%
  add_trace(y = ~ `4`, name = 'Rating 4') %>%
  add_trace(y = ~ `5`, name = 'Rating 5') %>%
  layout(yaxis = list(title = 'Count'), barmode = 'stack') %>%
  layout(title ="Count of Hospitals by Different Ownership and Rating" ,margin = list(b = 180), xaxis=list(title = "Hospital Ownership",tickangle = 30))
```
