---
title: "test_shiny"
author: "Carolina Downie"
date: "11/27/2017"
output: html_document
runtime: shiny
---

```{r, Carolina section 230 - 330 }
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(ggridges)
library(ggthemes)
library(forcats)
library(viridis)
library(plotly)
library(shiny)
library(httr)
library(jsonlite)

hospital_data_regions <- read_csv(file = "./data/Hospital_General_Information.csv", col_names = TRUE) %>% 
  clean_names() %>% 
  mutate(region = ifelse(grepl("ME|NH|VT|MA|RI|CT", state), "New England", ifelse(grepl("NY|PA|NJ", state), "Middle Atlantic", ifelse(grepl("WI|MI|IL|IN|OH", state), "East North Central", ifelse(grepl("ND|SD|NE|KS|MN|IA|MO", state), "West North Central", ifelse(grepl("DE|MD|DC|VA|WV|NC|SC|GA|FL", state), "South Atlantic", ifelse(grepl("KY|TN|MS|AL", state), "East South Central", ifelse(grepl("OK|TX|AR|LA", state), "West South Central", ifelse(grepl("ID|MT|WY|NV|UT|CO|AZ|NM", state), "Mountain", ifelse(grepl("AK|WA|OR|CA|HI", state), "Pacific", "U.S. Territories")))))))))) 

```

```{r}
regions <- hospital_data_regions %>% 
  distinct(region) %>% pull()
# selectInput widget
shiny::selectInput("region_choice", label = h3("Select Region"),
            choices = regions, selected = "New England")
```

```{r}
renderPlotly({ 
  hospital_data_regions %>%
  filter(hospital_overall_rating != "Not Available") %>%
  filter(region == input$region_choice) %>%
  mutate(hospital_overall_rating = as.numeric(hospital_overall_rating)) %>%
  group_by(region, state, hospital_overall_rating) %>%
  mutate(num_hospitals = n()) %>%
  plot_ly(x = ~hospital_overall_rating, y = ~num_hospitals,color = ~state, type = "bar") %>% 
  layout(title = "Number of hospitals per hospital rating, by state", margin = list(b = 75)) 
})







```
